apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.7.0
  - configs/kubeflow-config.yaml
  - configs/nginx-config.yaml
  - cluster-role.yaml
  - deployment.yaml
  - vs.yaml
  - authorizationpolicy.yaml

configMapGenerator:
  - behavior: replace
    files:
      - configs/spawner_ui_config.yaml
    name: jupyter-web-app-config
    namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true
