apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/experimental/ray/kuberay-operator/overlays/kubeflow?ref=v1.10.2

patchesStrategicMerge:
  - patches/sidecar-injection.yaml
