apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/kubeflow-roles/base?ref=v1.10.2

patches:
- path: drop-all.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-kubernetes-edit
    version: v1

- path: kubeflow-edit-rules.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-kubernetes-edit
    version: v1
