apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/applications/pvcviewer-controller/upstream/base?ref=v1.10.2

patches:
  - target:
      kind: Deployment
      name: pvcviewer-controller-manager
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value: []

      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GUNICORN_CMD_ARGS
          value: "--limit-request-field_size 32000"
