apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/oidc-authservice/base?ref=v1.7.0


patches:
- path: envoyfilter-patch.json
  target:
    group: networking.istio.io
    kind: EnvoyFilter
    name: authn-filter
    version: v1alpha3
- path: statefulset.yaml
- path: secret.yaml
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: oidc-authservice-parameters
    $patch: delete
