apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/manifests/applications/volumes-web-app/upstream/overlays/istio?ref=v1.10.2

patchesStrategicMerge:
  # TODO:
  #   Apply Auroraâ€™s updated AuthorizationPolicy for the Volumes Web App.
  #   This replaces the upstream rule that only allows traffic from the
  #   Istio ingress gateway and instead permits calls originating from the
  #   kubeflow-service-account, which is the actual identity used for
  #   internal UI-to-UI mesh communication in secure Kubeflow deployments.
  #   Required for correct functionality under Istio AuthorizationPolicy
  #   enforcement and zero-trust mesh configurations.
  - patches/authorization-policy.yaml
  - patches/virtual-service.yaml
