apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow
data:
  ingress: |-
    {
      "enableGatewayApi": false,
      "kserveIngressGateway": "",
      "ingressGateway": "ingress-kfserving/ingress-kubeflow-istio-ingress-gateway-https",
      "localGateway": "knative-serving/knative-local-gateway",
      "localGatewayService": "knative-local-gateway.istio-system.svc.cluster.local",
      "ingressDomain": "",
      "ingressClassName": "istio",
      "domainTemplate": "{{ .Name }}-{{ .Namespace }}",
      "urlScheme": "https",
      "disableIstioVirtualHost": false,
      "disableIngressCreation": false
    }
