apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=v1.7.0


configMapGenerator:
- behavior: merge
  envs:
  - params.env
  name: config
patches:
- path: deployment.yaml
